# Generated by Django 4.0 on 2022-02-19 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.CharField(default=None, max_length=300, null=True)),
                ('ansewr_count', models.PositiveIntegerField(default=0, max_length=10)),
                ('scope', models.PositiveIntegerField(max_length=1)),
                ('start_at', models.DateField(default=django.utils.timezone.localdate, null=True)),
                ('end_at', models.DateField(default=None, null=True)),
            ],
            options={
                'db_table': 'questionnaire',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('questionnaire.questionnaire',),
        ),
    ]
