# Generated by Django 4.0 on 2022-04-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordhistory',
            name='count_this_week',
            field=models.PositiveIntegerField(default=0, max_length=10),
        ),
    ]
