# Generated by Django 4.0 on 2022-02-19 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
