# Generated by Django 4.0 on 2022-02-19 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_alter_category_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.category')),
                ('questionnaire_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaire')),
            ],
            options={
                'db_table': 'category_mapping',
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='categorymapping',
            constraint=models.UniqueConstraint(fields=('questionnaire_id', 'category_id'), name='mapping_unique'),
        ),
    ]
