# Generated by Django 4.0 on 2022-02-24 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_categorymappingproxy_categoryproxy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='ansewr_count',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='answer_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)]),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='scope',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
