# Generated by Django 4.0 on 2022-04-09 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_remove_questionnaire_ansewr_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='watched_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
